version: '2'
services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        volumes:
            - ./templates:/templates
    db:
        image: mongo
